name: reusable/analysis
on:
  workflow_call:
    inputs:
      moduleRootDirectory:
        description: "Defines root module directory"
        required: true
        type: string

    secrets:
      githubToken:
        description: "GitHub Token value"
        required: true

jobs:
  tfsec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.moduleRootDirectory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan module with tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.moduleRootDirectory }}
          github_token: ${{ secrets.githubToken }}
